### ISSUE TITLE
运行的相关问题

### ISSUE THREAD

**Issue by OnePl3** [christorange/QC-CNN#1]
老哥

运行项目的时候 Devices是不是不能选择cuda
我看选用cuda后 optimizer.step()那边报错：
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

量子微分是不是目前不能在gpu上 【基于pennylane】

**Comment by OnePl3** [comment]
我发现问题所在了 非常感谢您开源的项目

**Comment by christorange** [comment]
不客气！顺便补充下， Pennylane 虽然支持gpu加速，但是官方宣称只有在 qubit 数目大于 15 时才有加速效果，[否则会比cpu还慢](https://docs.pennylane.ai/en/stable/introduction/interfaces/torch.html)。但是你可以尝试下 [Pennylane-Lightning-GPU](https://github.com/PennyLaneAI/pennylane-lightning-gpu)，这个插件基于 c++写成的 pennylane-lightning 模拟器调用了 NVIDIA cuQuantum SDK，就是要配置下 c++ 环境，以及根据社区反馈运行的精度与结果可能与原生内置的模拟器有差别
