### ISSUE TITLE
博主你好，我想问一些问题

### ISSUE THREAD

**Issue by XiangGaofeng** [christorange/QC-CNN#3]
因为最近导师给的方向是经典神经网络加一点量子，那么对于传统的目标检测，比如ssd算法的话，我现在想的是将传统的2d卷积换成量子卷积，但是我觉得因为输入会很大，比如对一个30*30*256的输入进行量子卷积，输出成15*15*256的，使用量子卷积的话，可以实现出来嘛

**Comment by christorange** [comment]
是可行的，很多文章都宣称使用了 28 × 28 的 MNIST 数据集进行模拟，但是他们的代码和我不同。这个项目里我尝试过用 28×28 的灰度图片，但是会报内存溢出错误，所以才做了下采样。你可能需要比较强大的机器来模拟，而且会算得很慢
