### ISSUE TITLE
Why this happen?What should I do to solve it?

### ISSUE THREAD

**Issue by Pride-Huang** [christorange/QC-CNN#4]
![image](https://user-images.githubusercontent.com/34713001/222882307-7d86688f-db08-418c-ab6e-abd10dd4b86f.png)

**Comment by Pride-Huang** [comment]
this problem is solved, and it dues to the python version. However, new problem happened.
![image](https://user-images.githubusercontent.com/34713001/222885583-62505a03-7857-4a54-8ec5-a7daabc82116.png)

**Comment by christorange** [comment]
downgrade pennylane to v0.23.0
then downgrade autoray to v0.2.5

check the dependency section in readme for details

**Comment by Pride-Huang** [comment]
> downgrade pennylane to v0.23.0 then downgrade autoray to v0.2.5
> 
> check the dependency section in readme for details

Thanks. It solved my problem.
